name: build

on:
  pull_request:
  workflow_run:
    workflows: ["Github workflow test"]
    types: [completed]
  workflow_dispatch:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: openquantumsafe/go
          tags: |
              type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: false
          tags: openquantumsafe/go
          labels: ${{ steps.meta.outputs.labels }}