name: pr_build

on:
  pull_request:
  workflow_run:
    workflows: ["Github workflow test"]
    types: [completed]
    
jobs:
  build-image-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ghcr.io/open-quantum-safe/liboqs-go
          tags: |
              type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/open-quantum-safe/liboqs-go
          labels: ${{ steps.meta.outputs.labels }}